Remove 'Test' section from README (#3)
* Remove 'Test' section from README

Remove 'Test' section from the README.

* Disable username validation in GitHub Actions

Comment out GitHub username validation step in workflow

* Fix GitHub Actions syntax for username and needs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,7 +1,7 @@
 name: Main workflow
 on: push
 env: # Set the secret as an input
-  github_username: ${{ lower(github.actor) }}
+  github_username: ${{ github.actor }}
   github_password: ${{ secrets.GITHUB_TOKEN }} # Must be made available to the workflow
   GIT_COMMIT: ${{ github.sha }}
 jobs:
@@ -9,16 +9,16 @@ jobs:
     runs-on: ubuntu-latest
     container: gradle:6-jdk11
     steps:
-      - name: Validate GitHub username is all lowercase
-        id: validate_lower
-        run: |
-          if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
-            echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
-            exit 1
-          else
-            echo "GitHub username format is valid."
-          fi
-        shell: bash
+    #  - name: Validate GitHub username is all lowercase
+    #    id: validate_lower
+    #    run: |
+    #      if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+    #        echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+    #        exit 1
+    #      else
+    #        echo "GitHub username format is valid."
+    #      fi
+    #    shell: bash
       - name: Clone down repository
         uses: actions/checkout@v4
       - name: Build application
@@ -33,8 +33,7 @@ jobs:
           include-hidden-files: true
   Linting:
     runs-on: ubuntu-latest
-    needs: 
-        - Build
+    needs: [Build]
     steps:
       - name: Clone down repository
         uses: actions/checkout@v4
@@ -66,7 +65,7 @@ jobs:
       run: bash ci/push-docker.sh
   Component-test:
     runs-on: ubuntu-latest
-    needs: Docker-image
+    needs: [Docker-image]
     steps:
     - name: Download code
       uses: actions/download-artifact@v4
