Disable username validation in GitHub Actions
Comment out GitHub username validation step in workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,16 +9,16 @@ jobs:
     runs-on: ubuntu-latest
     container: gradle:6-jdk11
     steps:
-      - name: Validate GitHub username is all lowercase
-        id: validate_lower
-        run: |
-          if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
-            echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
-            exit 1
-          else
-            echo "GitHub username format is valid."
-          fi
-        shell: bash
+    #  - name: Validate GitHub username is all lowercase
+    #    id: validate_lower
+    #    run: |
+    #      if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+    #        echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+    #        exit 1
+    #      else
+    #        echo "GitHub username format is valid."
+    #      fi
+    #    shell: bash
       - name: Clone down repository
         uses: actions/checkout@v4
       - name: Build application
